### ISSUE TITLE
? help command in julia repl not working

### ISSUE THREAD

**Issue by Aneeqasif** [wentasah/EmacsVterm.jl#4]
emacs throws error in minibuffer `Failed to find command: julia-repl--show.  To execute a command,
                add it to the ‘vterm-eval-cmd’ list`

if i type ?@time in julia repl

**Comment by wentasah** [comment]
Which version of [julia-repl](https://github.com/tpapp/julia-repl) do you have? Updating to a newer version might help.

**Comment by Aneeqasif** [comment]
i am not using juia repl i am using Julia-snail development environment and repl that it provides

**Comment by wentasah** [comment]
EmacsVterm.jl is designed to work with julia-repl. AFAIK julia-snail uses network sockets to communicate between Emacs and Julia and not the terminal, which is what EmacsVterm.jl provides. Is there anything missing in snail, which you want to implement via EmacsVterm.jl?

**Comment by Aneeqasif** [comment]
> Is there anything missing in snail, which you want to implement via EmacsVterm.jl?

It just gives error when i want to get the docs of something in the repl in snail as i have mentioned if i do 

`julia> ?@time` or get help for any other command.

**Comment by wentasah** [comment]
Then you have to either uninstall EmacsVterm or disable it by running `EmacsVterm.display_off()`.

**Comment by Aneeqasif** [comment]
Ok then iguess it only work with julia-repl. Thank you so much for your response.
